version: '3.8'
services:
  api:
    build: .
    container_name: estetica
    ports:
      - "3000:3005"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - .:/app
      - /app/node_modules